name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install poetry
      uses: actions/setup-python@v1
      run: |
        pip install -U pip
        pip install poetry

    - name: Install dependencies
      run: make init
